import PDFDocument from 'pdfkit';
import { formatPaise } from './billingEngine.js';

/**
 * Generates a styled PDF bill and pipes it to a response stream.
 * @param {object} bill      - Populated Bill document
 * @param {object} user      - User document
 * @param {object} org       - Organization document
 * @param {object} res       - Express response object
 */
export const generateBillPdf = async (bill, user, org, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="bill-${bill._id}.pdf"`);
  doc.pipe(res);

  // --- BRANDING HEADER: Logo or Initial ---
  if (org.logoUrl) {
    // If organization has a logo
    try {
      doc.image(org.logoUrl, 50, 45, { width: 50 });
      doc.moveDown();
    } catch (e) {
      // Fallback if image fails to load
      renderInitialLogo(doc, org);
    }
  } else {
    // Fallback: Styled Initial
    renderInitialLogo(doc, org);
  }

  doc.fontSize(22).fillColor(org.primaryColor || '#7C3AED').text(org.name, 110, 50, { align: 'left' });
  doc.fontSize(10).fillColor('#666').text('Utility Bill', 110, 75, { align: 'left' });
  doc.moveDown(2);

  // Bill metadata
  doc.fontSize(12).fillColor('#000');
  const meta = [
    ['Consumer', user.name],
    ['Consumer ID', user.consumerId],
    ['Meter No.', user.meterNumber || 'N/A'],
    ['Billing Period', `${bill.billingPeriod.month}/${bill.billingPeriod.year}`],
    ['Bill Date', new Date(bill.billDate).toLocaleDateString('en-IN')],
    ['Due Date', new Date(bill.dueDate).toLocaleDateString('en-IN')],
    ['Status', bill.status.toUpperCase()],
  ];

  let currentY = 120;
  meta.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').fontSize(10).text(`${label}: `, 50, currentY, { continued: true });
    doc.font('Helvetica').text(value);
    currentY += 15;
  });

  doc.moveDown(2);

  // Calculation breakdown table
  const tableTitleY = doc.y;
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#333').text('Calculation Breakdown', 50, tableTitleY);
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const col = [50, 150, 300, 430];
  doc.fontSize(10).fillColor('#555');
  doc.text('Units', col[0], tableTop, { width: 100 });
  doc.text('Rate (₹/unit)', col[1], tableTop, { width: 150 });
  doc.text('Charge', col[2], tableTop, { width: 130 });

  doc.moveTo(50, tableTop + 15).lineTo(540, tableTop + 15).stroke('#ccc');

  let rowY = tableTop + 25;
  bill.calculationBreakdown.forEach((row) => {
    doc.fillColor('#000').text(`${row.units} units`, col[0], rowY, { width: 100 });
    doc.text(formatPaise(row.rateInPaise * 100), col[1], rowY, { width: 150 });
    doc.text(formatPaise(row.chargeInPaise), col[2], rowY, { width: 130 });
    rowY += 20;
  });

  doc.moveTo(50, rowY).lineTo(540, rowY).stroke('#ccc');
  rowY += 15;

  // Totals
  const totals = [
    ['Fixed Charge', formatPaise(bill.fixedChargeInPaise || 0)],
    ['Subtotal', formatPaise(bill.subtotalInPaise)],
    ['Tax', formatPaise(bill.taxAmountInPaise)],
  ];

  totals.forEach(([label, value]) => {
    doc.fontSize(10).fillColor('#555').text(label, col[1], rowY, { width: 150 });
    doc.fillColor('#000').text(value, col[2], rowY, { width: 130 });
    rowY += 18;
  });

  // Total amount
  rowY += 10;
  doc.fontSize(14).font('Helvetica-Bold').fillColor(org.primaryColor || '#7C3AED')
    .text('Total Amount', col[1], rowY, { width: 150 });
  doc.text(formatPaise(bill.totalInPaise), col[2], rowY, { width: 130 });

  // --- SIGNATURE SECTION ---
  const footerY = 650;
  if (org.signatureUrl) {
    try {
      doc.image(org.signatureUrl, 400, footerY - 40, { width: 100 });
    } catch (e) {
      doc.fontSize(10).italic().text('Digitally Signed', 400, footerY - 10);
    }
  }
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#333').text('Authorized Signatory', 400, footerY);

  // --- CUSTOM FOOTER TEXT ---
  doc.moveTo(50, 750).lineTo(540, 750).stroke('#eee');
  doc.fontSize(9).font('Helvetica').fillColor('#999')
    .text(org.footerText || 'Generated by EnergI — Utility Billing Platform', 50, 765, { align: 'center', width: 490 });

  doc.end();
};

/**
 * Helper to render a styled initial as a fallback logo
 */
function renderInitialLogo(doc, org) {
  const initial = org.name ? org.name.charAt(0).toUpperCase() : 'E';
  const color = org.primaryColor || '#7C3AED';
  
  doc.circle(75, 65, 25).fill(color);
  doc.fontSize(25).font('Helvetica-Bold').fillColor('#fff').text(initial, 66, 52);
}