import PDFDocument from 'pdfkit';
import { formatPaise } from './billingEngine.js';

/**
 * Generates a styled PDF bill and pipes it to a response stream.
 * @param {object} bill      - Populated Bill document
 * @param {object} user      - User document
 * @param {object} org       - Organization document
 * @param {object} res       - Express response object
 */
export const generateBillPdf = (bill, user, org, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="bill-${bill._id}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(22).fillColor(org.primaryColor || '#7C3AED').text(org.name, { align: 'left' });
  doc.fontSize(10).fillColor('#666').text('Utility Bill', { align: 'left' });
  doc.moveDown();

  // Bill metadata
  doc.fontSize(12).fillColor('#000');
  const meta = [
    ['Consumer', user.name],
    ['Consumer ID', user.consumerId],
    ['Meter No.', user.meterNumber || 'N/A'],
    ['Billing Period', `${bill.billingPeriod.month}/${bill.billingPeriod.year}`],
    ['Bill Date', new Date(bill.billDate).toLocaleDateString('en-IN')],
    ['Due Date', new Date(bill.dueDate).toLocaleDateString('en-IN')],
    ['Status', bill.status],
  ];

  meta.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
    doc.font('Helvetica').text(value);
  });

  doc.moveDown();

  // Slab breakdown table
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#333').text('Calculation Breakdown');
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const col = [50, 150, 300, 430];
  doc.fontSize(10).fillColor('#555');
  doc.text('Units', col[0], tableTop, { width: 100 });
  doc.text('Rate (₹/unit)', col[1], tableTop, { width: 150 });
  doc.text('Charge', col[2], tableTop, { width: 130 });

  doc.moveTo(50, tableTop + 15).lineTo(540, tableTop + 15).stroke('#ccc');

  let rowY = tableTop + 20;
  bill.calculationBreakdown.forEach((row) => {
    doc.fillColor('#000').text(`${row.units} units`, col[0], rowY, { width: 100 });
    doc.text(formatPaise(row.rateInPaise * 100), col[1], rowY, { width: 150 }); // rateInPaise is per unit
    doc.text(formatPaise(row.chargeInPaise), col[2], rowY, { width: 130 });
    rowY += 18;
  });

  doc.moveTo(50, rowY).lineTo(540, rowY).stroke('#ccc');
  rowY += 10;

  // Totals
  const totals = [
    ['Fixed Charge', formatPaise(bill.fixedChargeInPaise || 0)],
    ['Subtotal', formatPaise(bill.subtotalInPaise)],
    ['Tax', formatPaise(bill.taxAmountInPaise)],
  ];

  totals.forEach(([label, value]) => {
    doc.fontSize(10).fillColor('#555').text(label, col[1], rowY, { width: 150 });
    doc.fillColor('#000').text(value, col[2], rowY, { width: 130 });
    rowY += 16;
  });

  // Total amount
  rowY += 8;
  doc.fontSize(14).font('Helvetica-Bold').fillColor(org.primaryColor || '#7C3AED')
    .text('Total Amount', col[1], rowY, { width: 150 });
  doc.text(formatPaise(bill.totalInPaise), col[2], rowY, { width: 130 });

  // Footer
  doc.moveDown(3);
  doc.fontSize(9).fillColor('#999').text('Generated by EnergI — Utility Billing Platform', { align: 'center' });

  doc.end();
};
